---
- name: Update Ubuntu system packages
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
 
    - name: Upgrade all packages
      apt:
        upgrade: safe
